version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cosc2767-network

  backend:
    image: backend-server
    container_name: backend
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - cosc2767-network
    command: >
      sh -c "npm start & 
             sleep 5 && 
             npm --prefix . run seed:db admin@rmit.edu.vn mypassword &&
             wait"

  frontend:
    image: client-side
    container_name: frontend
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cosc2767-network

volumes:
  mongo_data:

networks:
  cosc2767-network:
    driver: bridge
