---
- name: Prepare production build (backend + frontend)
  hosts: testing
  become: yes
  vars:
    repo_dest: "/root/COSC2767-RMIT-Store"
    api_url_production: "TestingALB-226086454.us-east-1.elb.amazonaws.com:300"
    dockerhub_user: "phg02"
    backend_image: "backendserver"
    frontend_image: "clientside"

  tasks:
    - name: Override .env for production
      lineinfile:
        path: "{{ repo_dest }}/client/.env"
        regexp: '^API_URL='
        line: "API_URL={{ api_url_production }}"
        create: yes

    - name: Build backend image
      command: docker build -t {{ backend_image }}:latest ./server
      args:
        chdir: "{{ repo_dest }}"

    - name: Build frontend image
      command: docker build -t {{ frontend_image }}:latest ./client
      args:
        chdir: "{{ repo_dest }}"

    - name: Tag backend image for Docker Hub
      command: docker tag {{ backend_image }}:latest {{ dockerhub_user }}/{{ backend_image }}:latest

    - name: Tag frontend image for Docker Hub
      command: docker tag {{ frontend_image }}:latest {{ dockerhub_user }}/{{ frontend_image }}:latest