- name: Push backend and frontend images to Docker Hub
  hosts: testing
  become: yes
  vars:
    dockerhub_user: "phg02"
    backend_image: "backendserver"
    frontend_image: "clientside"

  tasks:

    # ----------------- Push Backend Image -----------------
    - name: Push backend image
      command: docker push {{ dockerhub_user }}/{{ backend_image }}:latest
      register: backend_push_result
      failed_when: backend_push_result.rc != 0
      ignore_errors: no

    - name: Print backend push output
      debug:
        msg: "{{ backend_push_result.stdout }}"

    - name: Fail if backend push failed
      fail:
        msg: "Failed to push backend image to Docker Hub. Stopping deployment."
      when: backend_push_result.rc != 0

    # ----------------- Push Frontend Image -----------------
    - name: Push frontend image
      command: docker push {{ dockerhub_user }}/{{ frontend_image }}:latest
      register: frontend_push_result
      failed_when: frontend_push_result.rc != 0
      ignore_errors: no

    - name: Print frontend push output
      debug:
        msg: "{{ frontend_push_result.stdout }}"

    - name: Fail if frontend push failed
      fail:
        msg: "Failed to push frontend image to Docker Hub. Stopping deployment."
      when: frontend_push_result.rc != 0