---
- name: Push backend and frontend images to Docker Hub
  hosts: testing
  become: yes
  vars:
    dockerhub_user: "phg02"
    backend_image: "backendserver"
    frontend_image: "clientside"

  tasks:
    - name: Push backend image
      command: docker push {{ dockerhub_user }}/{{ backend_image }}:latest

    - name: Push frontend image
      command: docker push {{ dockerhub_user }}/{{ frontend_image }}:latest
